### ISSUE TITLE
./gradlew cAT failed in sample

### ISSUE THREAD

**Issue by hannesa2** [usefulness/screenshot-tests-for-android#68]
You have no CI support, so I did a test run locally with `./gradlew cAT`
But it fails with

```
> Task :android:connectedDebugAndroidTest
Starting 2 tests on API_30_Google_Api(AVD) - 11

io.github.usefulnes.testing.screenshot.sample.ScreenshotsSampleActivityTest > testScreenshotEntireActivityWithoutAccessibilityMetadata[API_30_Google_Api(AVD) - 11] FAILED 
        java.lang.RuntimeException: Failed to create the directory /sdcard/screenshots/io.github.usefulness.testing.screenshot.sample.test/screenshots-default for screenshots. Is your sdcard directory read-only?
        at com.facebook.testing.screenshot.internal.ScreenshotDirectories.getSdcardDir(ScreenshotDirectories.java:119)

io.github.usefulnes.testing.screenshot.sample.ScreenshotsSampleActivityTest > testScreenshotEntireActivity[API_30_Google_Api(AVD) - 11] FAILED 
        java.lang.RuntimeException: Failed to create the directory /sdcard/screenshots/io.github.usefulness.testing.screenshot.sample.test/screenshots-default for screenshots. Is your sdcard directory read-only?
        at com.facebook.testing.screenshot.internal.ScreenshotDirectories.getSdcardDir(ScreenshotDirectories.java:119)
Tests on API_30_Google_Api(AVD) - 11 failed: There was 2 failure(s).

> Task :android:connectedDebugAndroidTest FAILED
```

**Comment by mateuszkwiecinski** [comment]
The library has exactly the same limitations as the [original](https://github.com/facebook/screenshot-tests-for-android) and it seems like you hit this: https://github.com/facebook/screenshot-tests-for-android/issues/224#issuecomment-501072359

You have to do the same as the CI pipeline does:
https://github.com/usefulness/screenshot-tests-for-android/blob/73f619fb9c230e13a21d6c49d09731f962616dc8/.github/workflows/pull_request.yml#L160-L162
I hope this helps 🤞

**Comment by hannesa2** [comment]
I didn't see that it's a fork. Anyway, thank you !

Btw, this looks very promising https://github.com/android/testing-samples/tree/main/ui/espresso/ScreenshotSample.
It's super fast, but I've to figure out, where the images are stored to be able to grab it from device

**Comment by hannesa2** [comment]
Here they are ! It's so easy 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/3314607/201466171-459d8206-2ccf-400f-ad13-ac24c466e51f.png">

**Comment by mateuszkwiecinski** [comment]
Great! I'm happy this works for you as well 🎉 

This is indeed a fork of https://github.com/facebook/screenshot-tests-for-android which I had to detach to be able to publish under my own credentials on mavencentral 🤷 The difference in features is this supports [Gradle Configuration Cache](https://docs.gradle.org/current/userguide/configuration_cache.html) (https://github.com/facebook/screenshot-tests-for-android/issues/307)

if you're looking for some guidance, I recommend reading their documentation: https://facebook.github.io/screenshot-tests-for-android/#getting-started 

However, if you're just considering to add screenshot testing, then I'd probably recommend using a different library: https://github.com/pedrovgs/Shot or even https://github.com/cashapp/paparazzi. 
This, while being maintained, has a couple of design flaws that make it non-ideal for long term projects :)
